server:
  port: 8089

scheduled:
  esmp:
    cron: 0 */5 * * * ?
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/winter?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    show-sql: true
  redis:
      host: localhost       # Redis服务器地址
      port: 6379            # Redis服务器连接端口
      database: 0           # Redis数据库索引（默认为0）
      password:             # Redis服务器连接密码（默认为空）
      lettuce:
        pool:
          max-active: 8     # 连接池最大连接数（使用负值表示没有限制）
          max-wait: 1ms     # 连接池最大阻塞等待时间（使用负值表示没有限制）       # 连接池中的最大空闲连接
          min-idle: 0
          max-idle: 8      # 连接池中的最小空闲连接

logging:
  level:
    com.dee.studyadmin.repository: debug
##session过期时间
session:
  expire_time: 1800